"""add updated_at on event and seperate field send_at on event_db

Revision ID: 23c1b2b0ff9b
Revises: 615268247c0d
Create Date: 2024-07-15 15:12:48.710576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23c1b2b0ff9b'
down_revision = '615268247c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('expected_sent_at', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('exactly_sent_at', sa.DateTime(), nullable=True))
    op.drop_index('idx_event_send_at_is_sent_is_failed_deleted_at', table_name='event')
    op.drop_index('ix_event_send_at', table_name='event')
    op.create_index('idx_expected_sent_at_is_sent_is_failed_deleted_at', 'event', ['expected_sent_at', 'is_sent', 'is_failed', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_event_exactly_sent_at'), 'event', ['exactly_sent_at'], unique=False)
    op.create_index(op.f('ix_event_expected_sent_at'), 'event', ['expected_sent_at'], unique=False)
    op.drop_column('event', 'send_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('send_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_event_expected_sent_at'), table_name='event')
    op.drop_index(op.f('ix_event_exactly_sent_at'), table_name='event')
    op.drop_index('idx_expected_sent_at_is_sent_is_failed_deleted_at', table_name='event')
    op.create_index('ix_event_send_at', 'event', ['send_at'], unique=False)
    op.create_index('idx_event_send_at_is_sent_is_failed_deleted_at', 'event', ['send_at', 'is_sent', 'is_failed', 'deleted_at'], unique=False)
    op.drop_column('event', 'exactly_sent_at')
    op.drop_column('event', 'expected_sent_at')
    # ### end Alembic commands ###
