"""Initial migration.

Revision ID: 615268247c0d
Revises: 8a7dab39d77b
Create Date: 2024-07-15 14:18:41.755389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615268247c0d'
down_revision = '8a7dab39d77b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_index('idx_event_send_at_is_sent_is_failed_deleted_at', 'event', ['send_at', 'is_sent', 'is_failed', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_event_is_failed'), 'event', ['is_failed'], unique=False)
    op.create_index(op.f('ix_event_is_sent'), 'event', ['is_sent'], unique=False)
    op.create_index(op.f('ix_event_send_at'), 'event', ['send_at'], unique=False)
    op.create_unique_constraint(None, 'event', ['event_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='unique')
    op.drop_index(op.f('ix_event_send_at'), table_name='event')
    op.drop_index(op.f('ix_event_is_sent'), table_name='event')
    op.drop_index(op.f('ix_event_is_failed'), table_name='event')
    op.drop_index('idx_event_send_at_is_sent_is_failed_deleted_at', table_name='event')
    op.drop_column('event', 'updated_at')
    # ### end Alembic commands ###
