"""Initial migration.

Revision ID: 8a7dab39d77b
Revises: 
Create Date: 2024-07-15 00:38:53.273592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a7dab39d77b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('event_id', sa.String(length=50), nullable=False),
    sa.Column('email_subject', sa.String(length=120), nullable=False),
    sa.Column('email_content', sa.Text(), nullable=False),
    sa.Column('recipients', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('send_at', sa.DateTime(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('is_failed', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
